# Generated by Django 4.2.3 on 2023-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
